name: stactools-pointcloud
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::gdal<=3.11.1
  - conda-forge::pdal>=2.8
  - conda-forge::python-pdal>=3.2
  - conda-forge::geos>=3.3
  - conda-forge::rasterio>=1.4
  - conda-forge::libstdcxx-ng # gdal dependency. Make sure it's from the same channel as gdal
  - conda-forge::libarchive # pdal dependency. Make sure it's from the same channel as pdal
